import type { ReportAiImportSheet } from '../domain/reports/reportAiImport';
import type { ReportAiMasters } from '../domain/reports/reportAiMasters';

/**
 * テスト専用: 日報AIの調整のマスターの小さな架空のデータ(お客様の実際のマスターの文言は使わない。列の形だけ同じ)。
 * - K01: 0〜84か月・★3〜5・PSI 3以上(全年齢の語)
 * - K02: 36〜84か月・★4〜5・PSI 3以上
 * - K03: 0〜48か月・★5だけ・PSI 4以上(専門語)
 * - K04: 12〜72か月・★2〜5・PSI 3以上
 * 年齢帯は 0-12か月 / 1歳(12〜24) / 3歳(36〜48)。
 */
export function reportAiFixtureMasters(): ReportAiMasters {
  return {
    keywords: [
      {
        id: '00000000-0000-7000-8000-00000000a001',
        code: 'K01',
        category: 'テスト分類',
        keyword: '見守りの語',
        subConcept: null,
        ageLabel: '0〜6歳',
        ageFromMonths: 0,
        ageToMonths: 84,
        ageBandLabel: '全年齢',
        educationLevelMin: 3,
        educationLevelMax: 5,
        psiMin: 3,
        tone: '主体性・見守り',
        parentExplanation: '見守ることの説明。',
        phraseExamples: '① 例文その一。\n② 例文その二。',
        usageScene: '遊ぶ場面',
        ngExample: '評価の言い方',
        sortOrder: 0,
      },
      {
        id: '00000000-0000-7000-8000-00000000a002',
        code: 'K02',
        category: 'テスト分類',
        keyword: '協力の語',
        subConcept: null,
        ageLabel: '3〜6歳',
        ageFromMonths: 36,
        ageToMonths: 84,
        ageBandLabel: '3・4・5・6歳',
        educationLevelMin: 4,
        educationLevelMax: 5,
        psiMin: 3,
        tone: '意味づけ',
        parentExplanation: '協力の説明。',
        phraseExamples: '一緒に作る姿に見入りました。',
        usageScene: null,
        ngExample: null,
        sortOrder: 1,
      },
      {
        id: '00000000-0000-7000-8000-00000000a003',
        code: 'K03',
        category: '専門',
        keyword: '専門の語',
        subConcept: '専門の概念',
        ageLabel: '0〜3歳',
        ageFromMonths: 0,
        ageToMonths: 48,
        ageBandLabel: null,
        educationLevelMin: 5,
        educationLevelMax: 5,
        psiMin: 4,
        tone: '意味づけ',
        parentExplanation: '専門の語のやさしい説明。',
        phraseExamples: null,
        usageScene: null,
        ngExample: null,
        sortOrder: 2,
      },
      {
        id: '00000000-0000-7000-8000-00000000a004',
        code: 'K04',
        category: 'テスト分類',
        keyword: '指先の語',
        subConcept: null,
        ageLabel: '1〜5歳',
        ageFromMonths: 12,
        ageToMonths: 72,
        ageBandLabel: null,
        educationLevelMin: 2,
        educationLevelMax: 5,
        psiMin: 3,
        tone: null,
        parentExplanation: '指先の説明。',
        phraseExamples: null,
        usageScene: null,
        ngExample: null,
        sortOrder: 3,
      },
    ],
    ageBands: [
      {
        id: '00000000-0000-7000-8000-00000000b001',
        label: '0-12ヶ月',
        ageFromMonths: 0,
        ageToMonths: 12,
        behaviorWords: '見つめる／声を出す',
        developmentTopics: '首すわり',
        keywordCodes: ['K03', 'K01'],
        sceneExamples: '見守り',
        sortOrder: 0,
      },
      {
        id: '00000000-0000-7000-8000-00000000b002',
        label: '1歳',
        ageFromMonths: 12,
        ageToMonths: 24,
        behaviorWords: '歩く／指差し',
        developmentTopics: '歩き始め',
        keywordCodes: ['K04', 'K01'],
        sceneExamples: 'お散歩',
        sortOrder: 1,
      },
      {
        id: '00000000-0000-7000-8000-00000000b003',
        label: '3歳',
        ageFromMonths: 36,
        ageToMonths: 48,
        behaviorWords: 'なぜ？どうして？',
        developmentTopics: 'なぜなぜ期',
        keywordCodes: ['K02'],
        sceneExamples: null,
        sortOrder: 2,
      },
    ],
    educationLevels: [
      {
        level: 2,
        label: '標準',
        customerProfile: null,
        usage: '平易な語を1つまで',
        wordScope: null,
        termNameRule: '用語名は出さない',
        termNamePolicy: 'forbid',
        keywordsMin: 0,
        keywordsMax: 1,
        toneFocus: '日常＋ひとこと',
        exampleDirection: null,
      },
      {
        level: 5,
        label: '非常に高い',
        customerProfile: null,
        usage: '専門語を説明つきで',
        wordScope: null,
        termNameRule: '用語名を積極活用（説明必須）',
        termNamePolicy: 'allow',
        keywordsMin: 1,
        keywordsMax: 3,
        toneFocus: null,
        exampleDirection: null,
      },
    ],
    psiLevels: [{ level: 3, label: '要観察(テスト)', criteria: '少し気になる' }],
    phrases: [
      {
        id: '00000000-0000-7000-8000-00000000c001',
        kind: 'warm',
        body: 'ねぎらいの言葉。',
        message: 'ねぎらい',
        psiMin: 1,
        psiMax: 4,
        note: '締めに',
        sortOrder: 0,
      },
      {
        id: '00000000-0000-7000-8000-00000000c002',
        kind: 'warm',
        body: '休んでほしい言葉。',
        message: '休息',
        psiMin: 1,
        psiMax: 2,
        note: null,
        sortOrder: 1,
      },
      {
        id: '00000000-0000-7000-8000-00000000c003',
        kind: 'warm',
        body: 'また会いたい言葉。',
        message: null,
        psiMin: 1,
        psiMax: 5,
        note: null,
        sortOrder: 2,
      },
      {
        id: '00000000-0000-7000-8000-00000000c004',
        kind: 'avoid',
        body: '次回は〜しましょう',
        message: '宿題に聞こえる',
        psiMin: 1,
        psiMax: 5,
        note: null,
        sortOrder: 3,
      },
    ],
    stanceRules: [
      {
        id: '00000000-0000-7000-8000-00000000d001',
        topic: '評価口調',
        avoidText: '〜が育っています',
        recommendedText: 'こちらまで息をのみました',
        reason: '評価者にならない',
        sortOrder: 0,
      },
    ],
  };
}

/**
 * お客様の「日報キーワード表現マスター」と同じ見出し・同じ並び(1行目が注記の結合セルのシートを含む)の、
 * 架空の中身の小さな表。
 */
export function syntheticMasterSheets(): ReportAiImportSheet[] {
  return [
    { name: '00_使い方', rows: [['日報キーワード・表現 マスター'], ['■ 基本の考え方']] },
    {
      name: '01_マスター表',
      rows: [
        [
          'ID',
          'カテゴリ',
          'キーワード',
          'サブ概念',
          '対象年齢(表示)',
          '年齢下限_月齢',
          '年齢上限_月齢',
          '適用年齢帯',
          '教育思考レベル適用★',
          'PSI下限(この値以上で使用可)',
          'トーン種別',
          '親向け説明（やさしい言い換え）',
          '日報フレーズ例（見ていた人スタンス）',
          '使いどころ・場面',
          'この語でのNG例（避ける上から目線）',
        ],
        [
          'K01',
          '分類A',
          '語A',
          '概念A',
          '3〜6歳',
          36,
          84,
          '3・4・5・6歳',
          '4-5',
          3,
          '意味づけ',
          '説明A',
          '① 例A1\n② 例A2',
          '場面A',
          'NG A',
        ],
        [
          'K02',
          '分類A',
          '語B',
          null,
          '0〜6歳',
          0.0,
          84.0,
          '全年齢',
          '3-5',
          3.0,
          '安心・愛着',
          '説明B',
          '例B',
          null,
          null,
        ],
        ['K03', '分類B', '語C', null, '0〜3歳', 0, 48, null, '5-5', 4, null, '説明C', null, null, null],
      ],
    },
    {
      name: '02_年齢帯定義',
      rows: [
        [
          '年齢帯',
          '月齢範囲',
          'この時期によく描写する行動・単語',
          '発達の主なトピック',
          '相性の良いキーワードID',
          '場面例',
        ],
        ['0-6ヶ月', '0〜6ヶ月', '見つめる／声を出す', '首すわり', 'K02 K03', '見守り'],
        ['6-12ヶ月', '6〜12ヶ月', 'つかむ', 'お座り', 'K03', null],
        ['1歳', '12〜24ヶ月', '歩く', '歩き始め', 'K02', 'お散歩'],
      ],
    },
    {
      name: '03_教育思考レベル定義',
      rows: [
        [
          'レベル★',
          '呼称',
          '想定顧客像',
          '教育語の使い方',
          '使ってよい語の範囲',
          '用語名の扱い',
          '1通あたり教育語',
          'トーンの主眼',
          '例文の方向性',
        ],
        ['★1', '呼称1', '像1', '使い方1', '（教育語なし）', '用語名NG', '0個', '主眼1', '方向1'],
        ['★2', '呼称2', '像2', '使い方2', '範囲2', '用語名は出さない', '0〜1個', '主眼2', '方向2'],
        ['★3', '呼称3', '像3', '使い方3', '範囲3', '概念は説明、用語名は控えめ', '1個', null, null],
        ['★4', '呼称4', '像4', '使い方4', '範囲4', '用語名OK・必ず説明とセット', '1〜2個', null, null],
        [
          '★5',
          '呼称5',
          '像5',
          '使い方5',
          '範囲5',
          '用語名を積極活用（説明必須）',
          '1〜2個（詰め込みNG）',
          null,
          null,
        ],
      ],
    },
    {
      name: '04_PSI指標定義',
      rows: [
        ['※ PSI は保護者のストレス度。\nPSIは教育スコアに優先します。', null, null],
        ['評価', '定義', '判定基準'],
        ['5', '定義5', '基準5'],
        ['4', '定義4', '基準4'],
        ['3', '定義3', '基準3'],
        ['2', '定義2', '基準2'],
        ['1', '定義1', '基準1'],
      ],
    },
    {
      name: '05_温かみ表現_PSI配慮',
      rows: [
        ['※ ◎使う＝伴走トーン。✕避ける＝全ての日報で使わない。', null, null, null, null],
        ['区分', '表現例／避ける言い回し', '込めるメッセージ／理由', '推奨PSI・適用範囲', '備考'],
        ['◎使う', '温かい表現1', 'ねぎらい', '1〜4', '締めに'],
        ['◎使う', '温かい表現2', '関係', '全PSI可', null],
        ['✕避ける', '避ける表現1', '課題感', '全日報で不使用（PSI問わず）', '提案は控える'],
      ],
    },
    {
      name: '06_見ていた人スタンス_NG表現',
      rows: [
        ['項目', '✕避ける（上から目線・評価）', '◎推奨（見ていた人・共感）', '理由'],
        ['評価口調', '避ける1', '推奨1', '理由1'],
        ['締め', '避ける2', '推奨2', '理由2'],
      ],
    },
    {
      name: '07_参照フロー図',
      rows: [
        [null, '日報AIプロンプト　参照フロー'],
        [null, '1', '年齢帯を特定する'],
      ],
    },
  ];
}

/** プロンプト変更案の「参照ブロック_キーワード貼付用」シートと同じ見出しの表。 */
export function syntheticPasteBlockSheet(): ReportAiImportSheet {
  return {
    name: '③参照ブロック_キーワード貼付用',
    rows: [
      ['日報キーワード表(プロンプト末尾に貼り付け)', null, null, null, null, null, null, null],
      [
        'ID',
        'カテゴリ',
        'キーワード',
        '対象年齢\n(月齢)',
        '適用★',
        'PSI下限',
        '親向け説明（やさしい言い換え）',
        '日報フレーズ例（見ていた人スタンス）',
      ],
      ['K01', '分類A', '語A', '3-6歳(36-84)', '4-5', '3', '説明A2', '短い例A'],
      ['K09', '分類C', '語D', '全年齢(0-96)', '5', '4', '説明D', '短い例D'],
      ['■PSI指標：5=安心良好／1=危険緊急。', null, null, null, null, null, null, null],
    ],
  };
}
